/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AccountType = IDL.Variant({
  'both' : IDL.Null,
  'intraday' : IDL.Null,
  'delivery' : IDL.Null,
});
export const BrokerInput = IDL.Record({
  'accountId' : IDL.Text,
  'accountType' : AccountType,
  'brokerName' : IDL.Text,
});
export const BrokerId = IDL.Nat;
export const UserId = IDL.Principal;
export const BrokerAccount = IDL.Record({
  'id' : BrokerId,
  'accountId' : IDL.Text,
  'owner' : UserId,
  'accountType' : AccountType,
  'brokerName' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const AssetClass = IDL.Variant({
  'mutualFund' : IDL.Null,
  'equity' : IDL.Null,
});
export const HoldingInput = IDL.Record({
  'ticker' : IDL.Text,
  'purchasePrice' : IDL.Float64,
  'purchaseDate' : Timestamp,
  'companyName' : IDL.Text,
  'quantity' : IDL.Float64,
  'assetClass' : AssetClass,
});
export const HoldingId = IDL.Nat;
export const Holding = IDL.Record({
  'id' : HoldingId,
  'ticker' : IDL.Text,
  'purchasePrice' : IDL.Float64,
  'purchaseDate' : Timestamp,
  'owner' : UserId,
  'companyName' : IDL.Text,
  'quantity' : IDL.Float64,
  'assetClass' : AssetClass,
});
export const BenchmarkResult = IDL.Record({
  'sp500YtdReturn' : IDL.Float64,
  'portfolioYtdReturn' : IDL.Float64,
});
export const Action = IDL.Variant({
  'buy' : IDL.Null,
  'hold' : IDL.Null,
  'sell' : IDL.Null,
});
export const RiskRating = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const StockRecommendation = IDL.Record({
  'currentPrice' : IDL.Float64,
  'action' : Action,
  'ticker' : IDL.Text,
  'expectedReturn' : IDL.Float64,
  'riskRating' : RiskRating,
  'targetPrice' : IDL.Float64,
  'companyName' : IDL.Text,
});
export const PortfolioSummary = IDL.Record({
  'gainLossAmt' : IDL.Float64,
  'gainLossPct' : IDL.Float64,
  'totalInvestment' : IDL.Float64,
  'totalValue' : IDL.Float64,
});
export const RebalanceAlert = IDL.Record({
  'ticker' : IDL.Text,
  'targetPct' : IDL.Float64,
  'currentPct' : IDL.Float64,
  'driftPct' : IDL.Float64,
  'assetClass' : AssetClass,
});
export const TargetAllocation = IDL.Record({
  'targetPct' : IDL.Float64,
  'assetClass' : AssetClass,
});
export const RebalancingFrequency = IDL.Variant({
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const PortfolioSettingsView = IDL.Record({
  'name' : IDL.Text,
  'targetAllocations' : IDL.Vec(TargetAllocation),
  'rebalancingFrequency' : RebalancingFrequency,
  'riskFreeRate' : IDL.Float64,
  'cashBalance' : IDL.Float64,
  'initialInvestment' : IDL.Float64,
});
export const TaxBucket = IDL.Variant({
  'ltcg' : IDL.Null,
  'stcg' : IDL.Null,
  'unrealized' : IDL.Null,
});
export const TaxPosition = IDL.Record({
  'gainLossAmt' : IDL.Float64,
  'ticker' : IDL.Text,
  'taxLiability' : IDL.Float64,
  'holdingId' : HoldingId,
  'bucket' : TaxBucket,
});
export const TaxSummary = IDL.Record({
  'ltcgTax' : IDL.Float64,
  'stcgTax' : IDL.Float64,
  'unrealizedTotal' : IDL.Float64,
  'stcgTotal' : IDL.Float64,
  'positions' : IDL.Vec(TaxPosition),
  'ltcgTotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addBroker' : IDL.Func([BrokerInput], [BrokerAccount], []),
  'addHolding' : IDL.Func([HoldingInput], [Holding], []),
  'deleteHolding' : IDL.Func([HoldingId], [IDL.Bool], []),
  'getBenchmark' : IDL.Func([], [BenchmarkResult], ['query']),
  'getDailyRecommendations' : IDL.Func(
      [],
      [IDL.Vec(StockRecommendation)],
      ['query'],
    ),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
  'getRebalanceAlerts' : IDL.Func([], [IDL.Vec(RebalanceAlert)], ['query']),
  'getSettings' : IDL.Func([], [PortfolioSettingsView], ['query']),
  'getSharpeRatio' : IDL.Func([], [IDL.Float64], ['query']),
  'getTaxSummary' : IDL.Func([], [TaxSummary], ['query']),
  'getVolatility' : IDL.Func([], [IDL.Float64], ['query']),
  'listBrokers' : IDL.Func([], [IDL.Vec(BrokerAccount)], ['query']),
  'listHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
  'removeBroker' : IDL.Func([BrokerId], [IDL.Bool], []),
  'updateHolding' : IDL.Func([HoldingId, HoldingInput], [IDL.Bool], []),
  'updateSettings' : IDL.Func([PortfolioSettingsView], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AccountType = IDL.Variant({
    'both' : IDL.Null,
    'intraday' : IDL.Null,
    'delivery' : IDL.Null,
  });
  const BrokerInput = IDL.Record({
    'accountId' : IDL.Text,
    'accountType' : AccountType,
    'brokerName' : IDL.Text,
  });
  const BrokerId = IDL.Nat;
  const UserId = IDL.Principal;
  const BrokerAccount = IDL.Record({
    'id' : BrokerId,
    'accountId' : IDL.Text,
    'owner' : UserId,
    'accountType' : AccountType,
    'brokerName' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const AssetClass = IDL.Variant({
    'mutualFund' : IDL.Null,
    'equity' : IDL.Null,
  });
  const HoldingInput = IDL.Record({
    'ticker' : IDL.Text,
    'purchasePrice' : IDL.Float64,
    'purchaseDate' : Timestamp,
    'companyName' : IDL.Text,
    'quantity' : IDL.Float64,
    'assetClass' : AssetClass,
  });
  const HoldingId = IDL.Nat;
  const Holding = IDL.Record({
    'id' : HoldingId,
    'ticker' : IDL.Text,
    'purchasePrice' : IDL.Float64,
    'purchaseDate' : Timestamp,
    'owner' : UserId,
    'companyName' : IDL.Text,
    'quantity' : IDL.Float64,
    'assetClass' : AssetClass,
  });
  const BenchmarkResult = IDL.Record({
    'sp500YtdReturn' : IDL.Float64,
    'portfolioYtdReturn' : IDL.Float64,
  });
  const Action = IDL.Variant({
    'buy' : IDL.Null,
    'hold' : IDL.Null,
    'sell' : IDL.Null,
  });
  const RiskRating = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const StockRecommendation = IDL.Record({
    'currentPrice' : IDL.Float64,
    'action' : Action,
    'ticker' : IDL.Text,
    'expectedReturn' : IDL.Float64,
    'riskRating' : RiskRating,
    'targetPrice' : IDL.Float64,
    'companyName' : IDL.Text,
  });
  const PortfolioSummary = IDL.Record({
    'gainLossAmt' : IDL.Float64,
    'gainLossPct' : IDL.Float64,
    'totalInvestment' : IDL.Float64,
    'totalValue' : IDL.Float64,
  });
  const RebalanceAlert = IDL.Record({
    'ticker' : IDL.Text,
    'targetPct' : IDL.Float64,
    'currentPct' : IDL.Float64,
    'driftPct' : IDL.Float64,
    'assetClass' : AssetClass,
  });
  const TargetAllocation = IDL.Record({
    'targetPct' : IDL.Float64,
    'assetClass' : AssetClass,
  });
  const RebalancingFrequency = IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const PortfolioSettingsView = IDL.Record({
    'name' : IDL.Text,
    'targetAllocations' : IDL.Vec(TargetAllocation),
    'rebalancingFrequency' : RebalancingFrequency,
    'riskFreeRate' : IDL.Float64,
    'cashBalance' : IDL.Float64,
    'initialInvestment' : IDL.Float64,
  });
  const TaxBucket = IDL.Variant({
    'ltcg' : IDL.Null,
    'stcg' : IDL.Null,
    'unrealized' : IDL.Null,
  });
  const TaxPosition = IDL.Record({
    'gainLossAmt' : IDL.Float64,
    'ticker' : IDL.Text,
    'taxLiability' : IDL.Float64,
    'holdingId' : HoldingId,
    'bucket' : TaxBucket,
  });
  const TaxSummary = IDL.Record({
    'ltcgTax' : IDL.Float64,
    'stcgTax' : IDL.Float64,
    'unrealizedTotal' : IDL.Float64,
    'stcgTotal' : IDL.Float64,
    'positions' : IDL.Vec(TaxPosition),
    'ltcgTotal' : IDL.Float64,
  });
  
  return IDL.Service({
    'addBroker' : IDL.Func([BrokerInput], [BrokerAccount], []),
    'addHolding' : IDL.Func([HoldingInput], [Holding], []),
    'deleteHolding' : IDL.Func([HoldingId], [IDL.Bool], []),
    'getBenchmark' : IDL.Func([], [BenchmarkResult], ['query']),
    'getDailyRecommendations' : IDL.Func(
        [],
        [IDL.Vec(StockRecommendation)],
        ['query'],
      ),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
    'getRebalanceAlerts' : IDL.Func([], [IDL.Vec(RebalanceAlert)], ['query']),
    'getSettings' : IDL.Func([], [PortfolioSettingsView], ['query']),
    'getSharpeRatio' : IDL.Func([], [IDL.Float64], ['query']),
    'getTaxSummary' : IDL.Func([], [TaxSummary], ['query']),
    'getVolatility' : IDL.Func([], [IDL.Float64], ['query']),
    'listBrokers' : IDL.Func([], [IDL.Vec(BrokerAccount)], ['query']),
    'listHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
    'removeBroker' : IDL.Func([BrokerId], [IDL.Bool], []),
    'updateHolding' : IDL.Func([HoldingId, HoldingInput], [IDL.Bool], []),
    'updateSettings' : IDL.Func([PortfolioSettingsView], [], []),
  });
};

export const init = ({ IDL }) => { return []; };