/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountType = { 'both' : null } |
  { 'intraday' : null } |
  { 'delivery' : null };
export type Action = { 'buy' : null } |
  { 'hold' : null } |
  { 'sell' : null };
export type AssetClass = { 'mutualFund' : null } |
  { 'equity' : null };
export interface BenchmarkResult {
  'sp500YtdReturn' : number,
  'portfolioYtdReturn' : number,
}
export interface BrokerAccount {
  'id' : BrokerId,
  'accountId' : string,
  'owner' : UserId,
  'accountType' : AccountType,
  'brokerName' : string,
}
export type BrokerId = bigint;
export interface BrokerInput {
  'accountId' : string,
  'accountType' : AccountType,
  'brokerName' : string,
}
export interface Holding {
  'id' : HoldingId,
  'ticker' : string,
  'purchasePrice' : number,
  'purchaseDate' : Timestamp,
  'owner' : UserId,
  'companyName' : string,
  'quantity' : number,
  'assetClass' : AssetClass,
}
export type HoldingId = bigint;
export interface HoldingInput {
  'ticker' : string,
  'purchasePrice' : number,
  'purchaseDate' : Timestamp,
  'companyName' : string,
  'quantity' : number,
  'assetClass' : AssetClass,
}
export interface PortfolioSettingsView {
  'name' : string,
  'targetAllocations' : Array<TargetAllocation>,
  'rebalancingFrequency' : RebalancingFrequency,
  'riskFreeRate' : number,
  'cashBalance' : number,
  'initialInvestment' : number,
}
export interface PortfolioSummary {
  'gainLossAmt' : number,
  'gainLossPct' : number,
  'totalInvestment' : number,
  'totalValue' : number,
}
export interface RebalanceAlert {
  'ticker' : string,
  'targetPct' : number,
  'currentPct' : number,
  'driftPct' : number,
  'assetClass' : AssetClass,
}
export type RebalancingFrequency = { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export type RiskRating = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface StockRecommendation {
  'currentPrice' : number,
  'action' : Action,
  'ticker' : string,
  'expectedReturn' : number,
  'riskRating' : RiskRating,
  'targetPrice' : number,
  'companyName' : string,
}
export interface TargetAllocation {
  'targetPct' : number,
  'assetClass' : AssetClass,
}
export type TaxBucket = { 'ltcg' : null } |
  { 'stcg' : null } |
  { 'unrealized' : null };
export interface TaxPosition {
  'gainLossAmt' : number,
  'ticker' : string,
  'taxLiability' : number,
  'holdingId' : HoldingId,
  'bucket' : TaxBucket,
}
export interface TaxSummary {
  'ltcgTax' : number,
  'stcgTax' : number,
  'unrealizedTotal' : number,
  'stcgTotal' : number,
  'positions' : Array<TaxPosition>,
  'ltcgTotal' : number,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'addBroker' : ActorMethod<[BrokerInput], BrokerAccount>,
  'addHolding' : ActorMethod<[HoldingInput], Holding>,
  'deleteHolding' : ActorMethod<[HoldingId], boolean>,
  'getBenchmark' : ActorMethod<[], BenchmarkResult>,
  'getDailyRecommendations' : ActorMethod<[], Array<StockRecommendation>>,
  'getPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getRebalanceAlerts' : ActorMethod<[], Array<RebalanceAlert>>,
  'getSettings' : ActorMethod<[], PortfolioSettingsView>,
  'getSharpeRatio' : ActorMethod<[], number>,
  'getTaxSummary' : ActorMethod<[], TaxSummary>,
  'getVolatility' : ActorMethod<[], number>,
  'listBrokers' : ActorMethod<[], Array<BrokerAccount>>,
  'listHoldings' : ActorMethod<[], Array<Holding>>,
  'removeBroker' : ActorMethod<[BrokerId], boolean>,
  'updateHolding' : ActorMethod<[HoldingId, HoldingInput], boolean>,
  'updateSettings' : ActorMethod<[PortfolioSettingsView], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];