/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BrokerInput {
    accountId: string;
    accountType: AccountType;
    brokerName: string;
}
export type Timestamp = bigint;
export type BrokerId = bigint;
export interface TaxSummary {
    ltcgTax: number;
    stcgTax: number;
    unrealizedTotal: number;
    stcgTotal: number;
    positions: Array<TaxPosition>;
    ltcgTotal: number;
}
export interface TargetAllocation {
    targetPct: number;
    assetClass: AssetClass;
}
export interface PortfolioSummary {
    gainLossAmt: number;
    gainLossPct: number;
    totalInvestment: number;
    totalValue: number;
}
export interface BenchmarkResult {
    sp500YtdReturn: number;
    portfolioYtdReturn: number;
}
export interface RebalanceAlert {
    ticker: string;
    targetPct: number;
    currentPct: number;
    driftPct: number;
    assetClass: AssetClass;
}
export interface BrokerAccount {
    id: BrokerId;
    accountId: string;
    owner: UserId;
    accountType: AccountType;
    brokerName: string;
}
export type UserId = Principal;
export interface HoldingInput {
    ticker: string;
    purchasePrice: number;
    purchaseDate: Timestamp;
    companyName: string;
    quantity: number;
    assetClass: AssetClass;
}
export interface StockRecommendation {
    currentPrice: number;
    action: Action;
    ticker: string;
    expectedReturn: number;
    riskRating: RiskRating;
    targetPrice: number;
    companyName: string;
}
export interface PortfolioSettingsView {
    name: string;
    targetAllocations: Array<TargetAllocation>;
    rebalancingFrequency: RebalancingFrequency;
    riskFreeRate: number;
    cashBalance: number;
    initialInvestment: number;
}
export type HoldingId = bigint;
export interface Holding {
    id: HoldingId;
    ticker: string;
    purchasePrice: number;
    purchaseDate: Timestamp;
    owner: UserId;
    companyName: string;
    quantity: number;
    assetClass: AssetClass;
}
export interface TaxPosition {
    gainLossAmt: number;
    ticker: string;
    taxLiability: number;
    holdingId: HoldingId;
    bucket: TaxBucket;
}
export enum AccountType {
    both = "both",
    intraday = "intraday",
    delivery = "delivery"
}
export enum Action {
    buy = "buy",
    hold = "hold",
    sell = "sell"
}
export enum AssetClass {
    mutualFund = "mutualFund",
    equity = "equity"
}
export enum RebalancingFrequency {
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export enum RiskRating {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum TaxBucket {
    ltcg = "ltcg",
    stcg = "stcg",
    unrealized = "unrealized"
}
export interface backendInterface {
    addBroker(input: BrokerInput): Promise<BrokerAccount>;
    addHolding(input: HoldingInput): Promise<Holding>;
    deleteHolding(id: HoldingId): Promise<boolean>;
    getBenchmark(): Promise<BenchmarkResult>;
    getDailyRecommendations(): Promise<Array<StockRecommendation>>;
    getPortfolioSummary(): Promise<PortfolioSummary>;
    getRebalanceAlerts(): Promise<Array<RebalanceAlert>>;
    getSettings(): Promise<PortfolioSettingsView>;
    getSharpeRatio(): Promise<number>;
    getTaxSummary(): Promise<TaxSummary>;
    getVolatility(): Promise<number>;
    listBrokers(): Promise<Array<BrokerAccount>>;
    listHoldings(): Promise<Array<Holding>>;
    removeBroker(id: BrokerId): Promise<boolean>;
    updateHolding(id: HoldingId, input: HoldingInput): Promise<boolean>;
    updateSettings(update: PortfolioSettingsView): Promise<void>;
}
import type { AccountType as _AccountType, Action as _Action, AssetClass as _AssetClass, BrokerAccount as _BrokerAccount, BrokerId as _BrokerId, BrokerInput as _BrokerInput, Holding as _Holding, HoldingId as _HoldingId, HoldingInput as _HoldingInput, PortfolioSettingsView as _PortfolioSettingsView, RebalanceAlert as _RebalanceAlert, RebalancingFrequency as _RebalancingFrequency, RiskRating as _RiskRating, StockRecommendation as _StockRecommendation, TargetAllocation as _TargetAllocation, TaxBucket as _TaxBucket, TaxPosition as _TaxPosition, TaxSummary as _TaxSummary, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBroker(arg0: BrokerInput): Promise<BrokerAccount> {
        if (this.processError) {
            try {
                const result = await this.actor.addBroker(to_candid_BrokerInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BrokerAccount_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBroker(to_candid_BrokerInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BrokerAccount_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addHolding(arg0: HoldingInput): Promise<Holding> {
        if (this.processError) {
            try {
                const result = await this.actor.addHolding(to_candid_HoldingInput_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Holding_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHolding(to_candid_HoldingInput_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Holding_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteHolding(arg0: HoldingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHolding(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHolding(arg0);
            return result;
        }
    }
    async getBenchmark(): Promise<BenchmarkResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getBenchmark();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBenchmark();
            return result;
        }
    }
    async getDailyRecommendations(): Promise<Array<StockRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyRecommendations();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyRecommendations();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioSummary(): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary();
            return result;
        }
    }
    async getRebalanceAlerts(): Promise<Array<RebalanceAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRebalanceAlerts();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRebalanceAlerts();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<PortfolioSettingsView> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_PortfolioSettingsView_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_PortfolioSettingsView_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharpeRatio(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharpeRatio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharpeRatio();
            return result;
        }
    }
    async getTaxSummary(): Promise<TaxSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaxSummary();
                return from_candid_TaxSummary_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaxSummary();
            return from_candid_TaxSummary_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVolatility(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolatility();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolatility();
            return result;
        }
    }
    async listBrokers(): Promise<Array<BrokerAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBrokers();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBrokers();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHoldings(): Promise<Array<Holding>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHoldings();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHoldings();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeBroker(arg0: BrokerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBroker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBroker(arg0);
            return result;
        }
    }
    async updateHolding(arg0: HoldingId, arg1: HoldingInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHolding(arg0, to_candid_HoldingInput_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHolding(arg0, to_candid_HoldingInput_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSettings(arg0: PortfolioSettingsView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_PortfolioSettingsView_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_PortfolioSettingsView_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AccountType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Action_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Action): Action {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_AssetClass_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetClass): AssetClass {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_BrokerAccount_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BrokerAccount): BrokerAccount {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Holding_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Holding): Holding {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioSettingsView_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioSettingsView): PortfolioSettingsView {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_RebalanceAlert_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RebalanceAlert): RebalanceAlert {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_RebalancingFrequency_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RebalancingFrequency): RebalancingFrequency {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_RiskRating_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskRating): RiskRating {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_StockRecommendation_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockRecommendation): StockRecommendation {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TargetAllocation_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TargetAllocation): TargetAllocation {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_TaxBucket_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaxBucket): TaxBucket {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_TaxPosition_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaxPosition): TaxPosition {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TaxSummary_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaxSummary): TaxSummary {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _HoldingId;
    ticker: string;
    purchasePrice: number;
    purchaseDate: _Timestamp;
    owner: _UserId;
    companyName: string;
    quantity: number;
    assetClass: _AssetClass;
}): {
    id: HoldingId;
    ticker: string;
    purchasePrice: number;
    purchaseDate: Timestamp;
    owner: UserId;
    companyName: string;
    quantity: number;
    assetClass: AssetClass;
} {
    return {
        id: value.id,
        ticker: value.ticker,
        purchasePrice: value.purchasePrice,
        purchaseDate: value.purchaseDate,
        owner: value.owner,
        companyName: value.companyName,
        quantity: value.quantity,
        assetClass: from_candid_AssetClass_n15(_uploadFile, _downloadFile, value.assetClass)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPrice: number;
    action: _Action;
    ticker: string;
    expectedReturn: number;
    riskRating: _RiskRating;
    targetPrice: number;
    companyName: string;
}): {
    currentPrice: number;
    action: Action;
    ticker: string;
    expectedReturn: number;
    riskRating: RiskRating;
    targetPrice: number;
    companyName: string;
} {
    return {
        currentPrice: value.currentPrice,
        action: from_candid_Action_n20(_uploadFile, _downloadFile, value.action),
        ticker: value.ticker,
        expectedReturn: value.expectedReturn,
        riskRating: from_candid_RiskRating_n22(_uploadFile, _downloadFile, value.riskRating),
        targetPrice: value.targetPrice,
        companyName: value.companyName
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticker: string;
    targetPct: number;
    currentPct: number;
    driftPct: number;
    assetClass: _AssetClass;
}): {
    ticker: string;
    targetPct: number;
    currentPct: number;
    driftPct: number;
    assetClass: AssetClass;
} {
    return {
        ticker: value.ticker,
        targetPct: value.targetPct,
        currentPct: value.currentPct,
        driftPct: value.driftPct,
        assetClass: from_candid_AssetClass_n15(_uploadFile, _downloadFile, value.assetClass)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    targetAllocations: Array<_TargetAllocation>;
    rebalancingFrequency: _RebalancingFrequency;
    riskFreeRate: number;
    cashBalance: number;
    initialInvestment: number;
}): {
    name: string;
    targetAllocations: Array<TargetAllocation>;
    rebalancingFrequency: RebalancingFrequency;
    riskFreeRate: number;
    cashBalance: number;
    initialInvestment: number;
} {
    return {
        name: value.name,
        targetAllocations: from_candid_vec_n29(_uploadFile, _downloadFile, value.targetAllocations),
        rebalancingFrequency: from_candid_RebalancingFrequency_n32(_uploadFile, _downloadFile, value.rebalancingFrequency),
        riskFreeRate: value.riskFreeRate,
        cashBalance: value.cashBalance,
        initialInvestment: value.initialInvestment
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    targetPct: number;
    assetClass: _AssetClass;
}): {
    targetPct: number;
    assetClass: AssetClass;
} {
    return {
        targetPct: value.targetPct,
        assetClass: from_candid_AssetClass_n15(_uploadFile, _downloadFile, value.assetClass)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ltcgTax: number;
    stcgTax: number;
    unrealizedTotal: number;
    stcgTotal: number;
    positions: Array<_TaxPosition>;
    ltcgTotal: number;
}): {
    ltcgTax: number;
    stcgTax: number;
    unrealizedTotal: number;
    stcgTotal: number;
    positions: Array<TaxPosition>;
    ltcgTotal: number;
} {
    return {
        ltcgTax: value.ltcgTax,
        stcgTax: value.stcgTax,
        unrealizedTotal: value.unrealizedTotal,
        stcgTotal: value.stcgTotal,
        positions: from_candid_vec_n36(_uploadFile, _downloadFile, value.positions),
        ltcgTotal: value.ltcgTotal
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gainLossAmt: number;
    ticker: string;
    taxLiability: number;
    holdingId: _HoldingId;
    bucket: _TaxBucket;
}): {
    gainLossAmt: number;
    ticker: string;
    taxLiability: number;
    holdingId: HoldingId;
    bucket: TaxBucket;
} {
    return {
        gainLossAmt: value.gainLossAmt,
        ticker: value.ticker,
        taxLiability: value.taxLiability,
        holdingId: value.holdingId,
        bucket: from_candid_TaxBucket_n39(_uploadFile, _downloadFile, value.bucket)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BrokerId;
    accountId: string;
    owner: _UserId;
    accountType: _AccountType;
    brokerName: string;
}): {
    id: BrokerId;
    accountId: string;
    owner: UserId;
    accountType: AccountType;
    brokerName: string;
} {
    return {
        id: value.id,
        accountId: value.accountId,
        owner: value.owner,
        accountType: from_candid_AccountType_n7(_uploadFile, _downloadFile, value.accountType),
        brokerName: value.brokerName
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mutualFund: null;
} | {
    equity: null;
}): AssetClass {
    return "mutualFund" in value ? AssetClass.mutualFund : "equity" in value ? AssetClass.equity : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    hold: null;
} | {
    sell: null;
}): Action {
    return "buy" in value ? Action.buy : "hold" in value ? Action.hold : "sell" in value ? Action.sell : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): RiskRating {
    return "low" in value ? RiskRating.low : "high" in value ? RiskRating.high : "medium" in value ? RiskRating.medium : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
}): RebalancingFrequency {
    return "monthly" in value ? RebalancingFrequency.monthly : "daily" in value ? RebalancingFrequency.daily : "weekly" in value ? RebalancingFrequency.weekly : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ltcg: null;
} | {
    stcg: null;
} | {
    unrealized: null;
}): TaxBucket {
    return "ltcg" in value ? TaxBucket.ltcg : "stcg" in value ? TaxBucket.stcg : "unrealized" in value ? TaxBucket.unrealized : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    intraday: null;
} | {
    delivery: null;
}): AccountType {
    return "both" in value ? AccountType.both : "intraday" in value ? AccountType.intraday : "delivery" in value ? AccountType.delivery : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockRecommendation>): Array<StockRecommendation> {
    return value.map((x)=>from_candid_StockRecommendation_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RebalanceAlert>): Array<RebalanceAlert> {
    return value.map((x)=>from_candid_RebalanceAlert_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TargetAllocation>): Array<TargetAllocation> {
    return value.map((x)=>from_candid_TargetAllocation_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaxPosition>): Array<TaxPosition> {
    return value.map((x)=>from_candid_TaxPosition_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BrokerAccount>): Array<BrokerAccount> {
    return value.map((x)=>from_candid_BrokerAccount_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Holding>): Array<Holding> {
    return value.map((x)=>from_candid_Holding_n13(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_AssetClass_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetClass): _AssetClass {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_BrokerInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BrokerInput): _BrokerInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_HoldingInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HoldingInput): _HoldingInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_PortfolioSettingsView_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortfolioSettingsView): _PortfolioSettingsView {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_RebalancingFrequency_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RebalancingFrequency): _RebalancingFrequency {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_TargetAllocation_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TargetAllocation): _TargetAllocation {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticker: string;
    purchasePrice: number;
    purchaseDate: Timestamp;
    companyName: string;
    quantity: number;
    assetClass: AssetClass;
}): {
    ticker: string;
    purchasePrice: number;
    purchaseDate: _Timestamp;
    companyName: string;
    quantity: number;
    assetClass: _AssetClass;
} {
    return {
        ticker: value.ticker,
        purchasePrice: value.purchasePrice,
        purchaseDate: value.purchaseDate,
        companyName: value.companyName,
        quantity: value.quantity,
        assetClass: to_candid_AssetClass_n11(_uploadFile, _downloadFile, value.assetClass)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountId: string;
    accountType: AccountType;
    brokerName: string;
}): {
    accountId: string;
    accountType: _AccountType;
    brokerName: string;
} {
    return {
        accountId: value.accountId,
        accountType: to_candid_AccountType_n3(_uploadFile, _downloadFile, value.accountType),
        brokerName: value.brokerName
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    targetAllocations: Array<TargetAllocation>;
    rebalancingFrequency: RebalancingFrequency;
    riskFreeRate: number;
    cashBalance: number;
    initialInvestment: number;
}): {
    name: string;
    targetAllocations: Array<_TargetAllocation>;
    rebalancingFrequency: _RebalancingFrequency;
    riskFreeRate: number;
    cashBalance: number;
    initialInvestment: number;
} {
    return {
        name: value.name,
        targetAllocations: to_candid_vec_n45(_uploadFile, _downloadFile, value.targetAllocations),
        rebalancingFrequency: to_candid_RebalancingFrequency_n48(_uploadFile, _downloadFile, value.rebalancingFrequency),
        riskFreeRate: value.riskFreeRate,
        cashBalance: value.cashBalance,
        initialInvestment: value.initialInvestment
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    targetPct: number;
    assetClass: AssetClass;
}): {
    targetPct: number;
    assetClass: _AssetClass;
} {
    return {
        targetPct: value.targetPct,
        assetClass: to_candid_AssetClass_n11(_uploadFile, _downloadFile, value.assetClass)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetClass): {
    mutualFund: null;
} | {
    equity: null;
} {
    return value == AssetClass.mutualFund ? {
        mutualFund: null
    } : value == AssetClass.equity ? {
        equity: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    both: null;
} | {
    intraday: null;
} | {
    delivery: null;
} {
    return value == AccountType.both ? {
        both: null
    } : value == AccountType.intraday ? {
        intraday: null
    } : value == AccountType.delivery ? {
        delivery: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RebalancingFrequency): {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == RebalancingFrequency.monthly ? {
        monthly: null
    } : value == RebalancingFrequency.daily ? {
        daily: null
    } : value == RebalancingFrequency.weekly ? {
        weekly: null
    } : value;
}
function to_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TargetAllocation>): Array<_TargetAllocation> {
    return value.map((x)=>to_candid_TargetAllocation_n46(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
